### ISSUE TITLE
Where is the custom startpage files?

### ISSUE THREAD

**Issue by hard-shutdown** [qcasey/chromium-patches#2]
Hello, could you upload the custom startpage html file? I would like to see it. Additionally, cloning this would break it as I don't have your username lol. Thank you!

**Comment by qcasey** [comment]
The startpage is over here at [SalientStartpage](https://github.com/qcasey/salientstartpage). Fair warning: I didn't make it easy to use and in retrospect it isn't that good of a startpage 🙈

That being said any `.html` file will work with the startpage patch. The different paths is still an issue though. 

I wonder if I can make the path an environment variable...

**Comment by qcasey** [comment]
Actually I don't think that's possible while maintaining reproducibility in the PKGBUILD. I recommend forking this repo and making the changes to the patch to match your setup.

When updating chromium I usually only change the PKGBUILD. If you're using the AUR as well you'd just have to make similar updates to that PKGBUILD but with different checksums and urls. 

If you're not using the AUR your modified patches should work well into the future without any more updates.

**Comment by qcasey** [comment]
Compromise time!

I can change my startpage patch here to use `/var/lib/chromium-startpage/index.html`, that way I and anyone who wants to use this as-is can put their startpage in that directory and everything will run fine.

**Comment by hard-shutdown** [comment]
Well that is a good idea, but what if you could incorporate it into the code (Comments on how it's done ofc) like through a base64 URI? Chromium recognizes it at will still render it. Additionally, it's cross-os and cross-system.

**Comment by hard-shutdown** [comment]
Also, does that path work on Windows machines?

**Comment by qcasey** [comment]
> Also, does that path work on Windows machines?

No, good point.

> Well that is a good idea, but what if you could incorporate it into the code (Comments on how it's done ofc) like through a base64 URI? Chromium recognizes it at will still render it. Additionally, it's cross-os and cross-system.

Could you link to/write an example of that base64 uri being used? I can't imagine how that'd go.

Another alternative might be writing a chromium flag that could be set at runtime, what do you think of that?

**Comment by hard-shutdown** [comment]
Here's an example, take note of the URL Bar

![image](https://user-images.githubusercontent.com/59001842/153761919-097afcbb-3801-4f7f-8db0-0a6d73f794c3.png)

The Base64 URI is as follows:

```data:text/html;base64,PCFET0NUWVBFIGh0bWw+PGh0bWw+PGhlYWQ+PHRpdGxlPmI2NCBzdGFydHBhZ2U8L3RpdGxlPjwvaGVhZD48Ym9keT50aGlzIEhUTUwgc3RhcnRwYWdlIGlzIGluIGJyYXZlLCBjaHJvbWl1bSBiYXNlZCwgYW5kIHRoZSB1cmkgaXMgaW4gYmFzZSA2NCBmb3JtYXQuPC9ib2R5PjwvaHRtbD4=```

Decoded, it is a simple webpage.

```<!DOCTYPE html>
<html>
    <head>
        <title>b64 startpage</title>
    </head>
    <body>
        this HTML startpage is in brave, chromium based, and the uri is in base 64 format.
    </body>
</html>

**Comment by hard-shutdown** [comment]
Additionally, consider this patch:

```diff --git a/chrome/browser/ui/browser.cc b/chrome/browser/ui/browser.cc
index 24954ee7e..8f1656740 100644
--- a/chrome/browser/ui/browser.cc
+++ b/chrome/browser/ui/browser.cc
@@ -668,7 +668,7 @@ bool Browser::HasFindBarController() const {
 GURL Browser::GetNewTabURL() const {
   if (app_controller_)
     return app_controller_->GetAppStartUrl();
-  return GURL(chrome::kChromeUINewTabURL);
+  return GURL("data:text/html;base64,PCFET0NUWVBFIGh0bWw+PGh0bWw+PGhlYWQ+PHRpdGxlPmI2NCBzdGFydHBhZ2U8L3RpdGxlPjwvaGVhZD48Ym9keT50aGlzIEhUTUwgc3RhcnRwYWdlIGlzIGluIGJyYXZlLCBjaHJvbWl1bSBiYXNlZCwgYW5kIHRoZSB1cmkgaXMgaW4gYmFzZSA2NCBmb3JtYXQuPC9ib2R5PjwvaHRtbD4=");
 }
 
 gfx::Image Browser::GetCurrentPageIcon() const {
@@ -1811,6 +1811,9 @@ bool Browser::ShouldFocusLocationBarByDefault(WebContents* source) {
     if (virtual_url.SchemeIs(content::kViewSourceScheme))
       return false;
 
+    if (url == GURL(chrome::kChromeUINewTabURL))
+      return true;
+
     if ((url.SchemeIs(content::kChromeUIScheme) &&
          url.host_piece() == chrome::kChromeUINewTabHost) ||
         (virtual_url.SchemeIs(content::kChromeUIScheme) &&
diff --git a/chrome/browser/ui/focus_tab_after_navigation_helper.cc b/chrome/browser/ui/focus_tab_after_navigation_helper.cc
index 9fc474936..2ddc3d6e0 100644
--- a/chrome/browser/ui/focus_tab_after_navigation_helper.cc
+++ b/chrome/browser/ui/focus_tab_after_navigation_helper.cc
@@ -37,6 +37,11 @@ void FocusTabAfterNavigationHelper::ReadyToCommitNavigation(
 
 bool FocusTabAfterNavigationHelper::ShouldFocusTabContents(
     content::NavigationHandle* navigation) {
+
+  // Custom startpage 
+  if (navigation->GetURL() == GURL(chrome::kChromeUINewTabURL))
+    return false;
+    
   // Don't focus content in an inactive window or tab.
   Browser* browser = chrome::FindBrowserWithWebContents(web_contents());
   if (!browser)
diff --git a/chrome/browser/ui/toolbar/chrome_location_bar_model_delegate.cc b/chrome/browser/ui/toolbar/chrome_location_bar_model_delegate.cc
index d293bdf58..5a909b783 100644
--- a/chrome/browser/ui/toolbar/chrome_location_bar_model_delegate.cc
+++ b/chrome/browser/ui/toolbar/chrome_location_bar_model_delegate.cc
@@ -116,8 +116,8 @@ bool ChromeLocationBarModelDelegate::ShouldDisplayURL() const {
   }
 
   const auto is_ntp = [](const GURL& url) {
-    return url.SchemeIs(content::kChromeUIScheme) &&
-           url.host() == chrome::kChromeUINewTabHost;
+    return url == GURL(chrome::kChromeUINewTabURL) || (url.SchemeIs(content::kChromeUIScheme) &&
+           url.host() == chrome::kChromeUINewTabHost);
   };
 
   GURL url = entry->GetURL();
diff --git a/chrome/common/webui_url_constants.cc b/chrome/common/webui_url_constants.cc
index 1911569c8..aa6ec1af0 100644
--- a/chrome/common/webui_url_constants.cc
+++ b/chrome/common/webui_url_constants.cc
@@ -127,7 +127,7 @@ const char kChromeUINewTabPageURL[] = "chrome://new-tab-page/";
 const char kChromeUINewTabPageThirdPartyHost[] = "new-tab-page-third-party";
 const char kChromeUINewTabPageThirdPartyURL[] =
     "chrome://new-tab-page-third-party/";
-const char kChromeUINewTabURL[] = "chrome://newtab/";
+const char kChromeUINewTabURL[] = "data:text/html;base64,PCFET0NUWVBFIGh0bWw+PGh0bWw+PGhlYWQ+PHRpdGxlPmI2NCBzdGFydHBhZ2U8L3RpdGxlPjwvaGVhZD48Ym9keT50aGlzIEhUTUwgc3RhcnRwYWdlIGlzIGluIGJyYXZlLCBjaHJvbWl1bSBiYXNlZCwgYW5kIHRoZSB1cmkgaXMgaW4gYmFzZSA2NCBmb3JtYXQuPC9ib2R5PjwvaHRtbD4=";
 const char kChromeUIOmniboxHost[] = "omnibox";
 const char kChromeUIOmniboxURL[] = "chrome://omnibox/";
 const char kChromeUIPasswordManagerInternalsHost[] =```

This is, ultimately, the most cross-platform way to go, maybe modifiable via a flag if you could incorporate that.

**Comment by hard-shutdown** [comment]
Also, I'm getting into custom Chromium builds, I have just set up and build a stock chromium build (took 2 hours to build). When I make changes, do I have to do a full rebuild or does it automatically change only when I modified, because it doesn't seem realistic to wait for a build after changing one or two files.

**Comment by qcasey** [comment]
It should rebuild only what is modified, if I recall correctly.

**Comment by hard-shutdown** [comment]
Alright, thank you. I do believe it is a good idea to implement a "portable" custom startpage implementation. Have a great rest of your week!
